baseURL = "/"
languageCode = "en-us"
title = "chef.sh (Chef Workstation)"

theme = "chef"
staticDir = ["./static", "../chef-sh"]

sectionPagesMenu = ["main", "tools-reference"]

# To develop against a local copy of the chef hugo theme, uncomment this line
# and set the value to the parent directory of where you have checked out the
# chef-hugo-theme repository
# themesDir = ""
