driver:
  name: vagrant
  forward_agent: yes
  synced_folders:
    - ['..', '/home/vagrant/chef-workstation']
  customize:
    cpus: 2
    memory: 2048
    storagectl:
      - name: SATA Controller
        hostiocache: "on"

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    run_list: yum-epel::default
  - name: centos-6.6
    run_list: yum-epel::default
  - name: centos-5.11
    run_list: yum-epel::default
  - name: debian-7.8
    run_list: apt::default
  - name: debian-6.0.10
    run_list: apt::default
  - name: freebsd-10.1
    run_list: freebsd::portsnap
  - name: freebsd-9.3
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: chef-workstation-builder::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        build_user_home:     /home/vagrant
        build_dir:           /home/vagrant/chef-workstation/omnibus
        install_dir:         /opt/chef-workstation
