driver:
  name: vagrant
  forward_agent: yes
  synced_folders:
    - ['..', '/home/vagrant/chef-workstation']
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero

# only run one of these at a time if you are interested in using the
# omnibus package produced; the build process begins by cleaning up
# prior built artifacts in pkg/ which is shared across VMs
platforms:
  - name: centos-7
  - name: centos-6
  - name: debian-9
  - name: debian-8
  - name: debian-7
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: windows-2012r2
    driver:
      box: tas50/windows_2012r2

suites:
  - name: default
    run_list: chef-workstation-builder::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        build_user_home:     /home/vagrant
        build_dir:           /home/vagrant/chef-workstation/omnibus
        install_dir:         /opt/chef-workstation
