[build]
  ignore = "git diff --quiet HEAD^ HEAD www/"

[build.environment]
  HUGO_VERSION = "0.69.0"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.12"
  NODE_ENV = "development"

[build.processing]
  skip_processing = true

[context.deploy-preview]
  publish = "www/chef-web-docs/public"
  command = "make preview_netlify"

[context.production]
  publish = "www/netlify_production"
  command = ""
